#!/bin/bash

set -e

source ./helper/common

log=$LOG_PATH/send_event_transaction.log

title "EI event setup job using $1"

setup_job() {
  trap exit_handler EXIT

  pushd scripts >/dev/null || exit
  # Arguments: name, endpoint, address, account
  yarn create-job "$1" "$2" "$3" "$4" "$5" "$6" "$7" | tee "$log"
  popd >/dev/null || exit

  jid=$(grep <"$log" "Deployed Job" | awk '{print$4}')

}

# Arguments: name, endpoint, addresses, address, accountIds, bridge
setup_job "$1" "$2" "$3" "$4" "$5" "$6" "$7"
