#!/bin/bash

set -e

source ./helper/common

run() {
  trap exit_handler EXIT

  mkdir -p "$LOG_PATH"

  title "Initiating a fresh test"

  # Remove old volumes so we can run a fresh test
  reset

  start_docker

  add_ei

  # Run EI after access credentials has been generated
  run_ei

  login_chainlink

  # Arguments: bridge type, url
  ./helper/setup_bridge "zil-unixtime-bridge" "http://external-adapter-unixtime:8090"

  # Arguments: name endpoint, addresses, address, bridge
  ./helper/setup_job "zil-unixtime-job" "zil-ws" "0x56A7812f68cbF83194a4a777D2310Aa7A378C9D8" "" "zil-unixtime-bridge"

  title "Started up"
}

run
