#!/bin/bash

set -e

source ./helper/common

setup() {
  mkdir -p "$LOG_PATH"
  touch external_initiator.env

  title "Setting up test environment"

  pushd scripts >/dev/null || exit
  local log=$LOG_PATH/integration_setup.log
  yarn install
  yarn setup | tee "$log"
  popd >/dev/null || exit

  build_docker

  title "Done setting up test environment"
}

setup

run() {
  trap exit_handler EXIT

  touch external_initiator.env

  mkdir -p "$LOG_PATH"

  title "Initiating a fresh test"

  # Remove old volumes so we can run a fresh test
  reset

  start_docker

  add_ei

  # Run EI after access credentials has been generated
  run_ei

  login_chainlink

  # Arguments: bridge type, url
  ./helper/setup_bridge "zil-unixtime-bridge" "http://external-adapter-unixtime:8080"
  ./helper/setup_bridge "zil-rhine-gauge-bridge" "http://external-adapter-rhine_gauge:8080"

  # Arguments: name, endpoint, addresses, address, accountIds, bridge
  ./helper/setup_job "zil" "zil-ws" "0x10281c73644ea6749087720b2bf9c539a3a99bfb" "" "" "zil-unixtime-bridge"
  ./helper/setup_job "zil" "zil-ws" "0x1594fdfc6eb2a3dc710b8f65bb327c910d82577e" "" "" "zil-rhine-gauge-bridge"
  title "Started up"
}

run
