#!/bin/bash

set -e

source ./common

run() {
  trap exit_handler EXIT

  mkdir -p "$LOG_PATH"

  title "Initiating a fresh test"

  # Remove old volumes so we can run a fresh test
  reset

  start_docker

  add_ei

  # Run EI after access credentials has been generated
  run_ei

  login_chainlink

  # Address based
  # Arguments: name endpoint, addresses, address
  ./setup_job "zil" "zil-ws" "0x56A7812f68cbF83194a4a777D2310Aa7A378C9D8" ""

  # stop_docker

  title "Done running tests"
}

run
