#!/bin/bash

set -e

source ./helper/common

run_setup() {
  mkdir -p "$LOG_PATH"
  touch external_initiator.env

  title "Setting up test environment"

  pushd tmp >/dev/null || exit
  # Create empty EI .env file
  touch external_initiator.env
  popd >/dev/null || exit

  pushd scripts >/dev/null || exit
  local log=$LOG_PATH/integration_setup.log
  yarn install
  yarn setup | tee "$log"
  popd >/dev/null || exit

  build_docker

  title "Done setting up test environment"
}

run_setup
